In [1]:
import pandas as pd
import requests

In [2]:
requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US7page=1')

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

In [4]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

NameError: name 'response' is not defined

In [5]:
df.head()

NameError: name 'df' is not defined

In [6]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [7]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp_df,ignore_index=True)

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

In [8]:
df

Empty DataFrame
Columns: []
Index: []

In [9]:
df.shape

(0, 0)

In [10]:
df.to_csv('movies.csv')